# Generated by Django 5.0.1 on 2024-02-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_cartitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='unique_id',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='unique_id',
            new_name='cart_item_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='unique_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unique_id',
            new_name='order_item_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unique_id',
            new_name='product_id',
        ),
    ]
