# Generated by Django 5.0.1 on 2024-02-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='unique_id',
            new_name='user_id',
        ),
    ]
